---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ include "csi-didiyun-ebs.name" . }}-controller"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "csi-didiyun-ebs.labels" . | nindent 4 }}
  {{- with .Values.controller.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      {{- include "csi-didiyun-ebs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        {{- include "csi-didiyun-ebs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: "{{ include "csi-didiyun-ebs.name" . }}-controller"
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: csi-attacher
          image: "{{ .Values.attacher.image.name }}:{{ .Values.attacher.image.tag }}"
          imagePullPolicy: {{ .Values.attacher.image.pullPolicy }}
          args:
          - --v=5
          - --csi-address=/csi/csi.sock
          {{- if gt (int .Values.controller.replicas) 1 }}
          - "--leader-election"
          - "--leader-election-type=leases"
          {{- end }}
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{ with .Values.attacher.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}

        - name: csi-provisioner
          image: "{{ .Values.provisioner.image.name }}:{{ .Values.provisioner.image.tag }}"
          imagePullPolicy: {{ .Values.provisioner.image.pullPolicy }}
          args:
          - -v=5
          - --csi-address=/csi/csi.sock
          - --feature-gates=Topology=true
          {{- if gt (int .Values.controller.replicas) 1 }}
          - "--enable-leader-election"
          {{- end }}
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{ with .Values.provisioner.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}

        - name: csi-resizer
          image: "{{ .Values.resizer.image.name }}:{{ .Values.resizer.image.tag }}"
          imagePullPolicy: {{ .Values.resizer.image.pullPolicy }}
          args:
          - -v=5
          - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{ with .Values.resizer.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}

        - name: ebs
          image: "{{ .Values.driver.image.name }}:{{ .Values.driver.image.tag }}"
          imagePullPolicy: {{ .Values.driver.image.pullPolicy }}
          args:
          - --v=5
          - --endpoint=$(CSI_ENDPOINT)
          - --nodeid=$(KUBE_NODE_NAME)
          - --token=$(API_TOKEN)
          env:
          - name: CSI_ENDPOINT
            value: unix:///csi/csi.sock
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: API_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: {{ include "csi-didiyun-ebs.name" $ }}-api-token
          ports:
          - containerPort: 9898
            name: healthz
            protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          {{ with .Values.resizer.resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}

      volumes:
      - emptyDir: {}
        name: socket-dir
