kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "csi-didiyun-ebs.name" $ }}-api-token"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: driver
    {{- include "csi-didiyun-ebs.labels" . | nindent 4 }}
data:
  token: {{ .Values.config.apiToken | b64enc | quote }}
