{{ range .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/component: "storage-class-{{ .name }}"
    {{- include "csi-didiyun-ebs.labels" $ | nindent 4 }}
provisioner: didiyun-ebs.csi.supremind.com
parameters:
  regionID: {{ required "region is missing" .region | quote }}
  zoneID: {{ required "zone is missing" .zone | quote }}
  type: {{ required "type is missing" .type | quote }}
reclaimPolicy: {{ default "Retain" .reclaimPolicy }}
allowVolumeExpansion: {{ default true .allowVolumeExpansion }}
volumeBindingMode: Immediate
---
{{ end }}
